#!/usr/bin/env python3 

from multiprocessing import Process, Queue
from datetime import datetime
import socks, socket, subprocess, requests, pyfiglet, sys, argparse

def KsKnmap(min, max):

    try:

        for port in range(min, max):

            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            socket.setdefaulttimeout(3)

            result = s.connect_ex((url,port))

            if result == 0:
                print("Port {} is open".format(port))
                q.put(port)

            s.close()
                
    except KeyboardInterrupt:
        print("\n Exitting Program")
        sys.exit()

    except socket.gaierror:
        print("\n Hostname Could Not Be Resolved")
        sys.exit()

    except socket.error:
        print("\n Server not responding")
        sys.exit()

subprocess.run("clear")

ascii_banner = pyfiglet.figlet_format("KsKnmap")
OpenPorts = []
t1 = datetime.now()

print(ascii_banner)

def menu():

    for i in "1":

        global List
        global url
        url = input("IP to scan -> ")
        print("\nSelect ports to scan (Select an option between 1 and 4)\n\n1. First 1000 ports,\n2. TOP COMMON PORTS,\n3. ALL ports,\n4. Insert manually the ports to scan\n")
        nports = input("-> ")

        if nports == "1":
            List = [0, 251, 501, 751, 1001]

        elif nports == "2":
            a

        elif nports == "3":
            List = [0, 16339, 32768, 49107, 65536]

        elif nports == "4":
            List = []
            print("\nInsert the ports to scan separed by [,] ")
            manual = input("\n-> ").split(",")
            List2 = manual
            for i in range(len(List2)):
                t = int(List2[i])
                List.append(t)
            print(List)

        else:
            print("Please insert a valid option")

    print("\n" + "-" * 50)
    print("Scanning Target: " + url)
    print("Scanning started at:" + str(t1))
    print("-" * 50 + "\n")

menu()

if __name__ == "__main__":
    
    procs = []
    q = Queue()
    for i in range(4):
        proc = Process(target=KsKnmap, args=(List[i],List[i+1]))
        procs.append(proc)

    for proc in procs:
        proc.start()

    for proc in procs:
        proc.join()

while not q.empty():
    OpenPorts.append(q.get())

t2 = datetime.now()
TotalT = t2-t1

print("\n" + "-" * 50)
print(OpenPorts)
print("\nScan completed in {}".format(TotalT))
print("-" * 50)
